// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// bus_master_tx //
// ------------- //

#define bus_master_tx_wrap_target 0
#define bus_master_tx_wrap 4
#define bus_master_tx_pio_version 0

static const uint16_t bus_master_tx_program_instructions[] = {
            //     .wrap_target
    0x200d, //  0: wait   0 gpio, 13
    0x80a0, //  1: pull   block
    0x6108, //  2: out    pins, 8                [1]
    0xe301, //  3: set    pins, 1                [3]
    0xe300, //  4: set    pins, 0                [3]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bus_master_tx_program = {
    .instructions = bus_master_tx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = bus_master_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config bus_master_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bus_master_tx_wrap_target, offset + bus_master_tx_wrap);
    return c;
}
#endif

// ------------- //
// bus_master_rx //
// ------------- //

#define bus_master_rx_wrap_target 0
#define bus_master_rx_wrap 4
#define bus_master_rx_pio_version 0

static const uint16_t bus_master_rx_program_instructions[] = {
            //     .wrap_target
    0x200c, //  0: wait   0 gpio, 12
    0xe301, //  1: set    pins, 1                [3]
    0xe300, //  2: set    pins, 0                [3]
    0x4108, //  3: in     pins, 8                [1]
    0x8020, //  4: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bus_master_rx_program = {
    .instructions = bus_master_rx_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = bus_master_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config bus_master_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bus_master_rx_wrap_target, offset + bus_master_rx_wrap);
    return c;
}
#endif

